import { GoogleGenAI } from "@google/genai";

const ai = new GoogleGenAI({ apiKey: process.env.API_KEY });

/**
 * Edits an image based on a text prompt using Gemini 2.5 Flash Image.
 * 
 * @param base64Image - The base64 encoded string of the image (without the data URL prefix).
 * @param mimeType - The MIME type of the image (e.g., 'image/png').
 * @param prompt - The text instruction for editing.
 * @returns The base64 data URL of the generated image.
 */
export const editImageWithGemini = async (
  base64Image: string,
  mimeType: string,
  prompt: string
): Promise<string> => {
  try {
    const response = await ai.models.generateContent({
      model: 'gemini-2.5-flash-image',
      contents: {
        parts: [
          {
            inlineData: {
              data: base64Image,
              mimeType: mimeType,
            },
          },
          {
            text: prompt,
          },
        ],
      },
    });

    let generatedImageUrl = '';

    if (response.candidates?.[0]?.content?.parts) {
      for (const part of response.candidates[0].content.parts) {
        if (part.inlineData && part.inlineData.data) {
          const base64EncodeString = part.inlineData.data;
          // Use image/png as default response type unless specified otherwise, though usually consistent with input or generic.
          generatedImageUrl = `data:image/png;base64,${base64EncodeString}`;
          break; // Found the image, exit loop
        }
      }
    }

    if (!generatedImageUrl) {
      throw new Error("No image generated by the model.");
    }

    return generatedImageUrl;

  } catch (error) {
    console.error("Error editing image:", error);
    throw error;
  }
};